# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier("pos.academy.Yomang")

submission_information({
    price_tier: 0,
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false,
})

app_rating_config_path("./fastlane/metadata/app_store_rating_config.json")

submit_for_review(true)

automatic_release(true)

force(true)