# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  desc "Register new devices"
  lane :new_devices do
    register_devices(
      devices_file: "./fastlane/devices.txt",
      team_id: "Yomang"
    )
  end
  
  desc "Build app and upload to testflight"
  lane :beta do
    sync_code_signing(
      type: "appstore", 
      app_identifier: "pos.academy.Yomang",
      readonly: true
    )
    clear_derived_data
    increment_build_number(xcodeproj: "Yomang.xcodeproj")
    build_app
    upload_to_testflight
  end

  desc "Build app and release to App Store."
  lane :release do |options|
    if options[:v]
      sync_code_signing(
        type: "appstore", 
        app_identifier: "pos.academy.Yomang",
        readonly: true
      )
      increment_build_number(xcodeproj: "Yomang.xcodeproj")
      build_app(
        configuration: "Release"
      )
      deliver
      upload_to_app_store(
        app_version: options[:v],
        submit_for_review: true,
        force: true,
        automatic_release: true,
        skip_screenshots: true,
        skip_metadata: false
      )
    end
  end
end
